name: SMS Spam Classifier

on:
  push:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read

    env:
      CI_COMMIT_MESSAGE: "Continuous Integration Build Artifacts"
      CI_COMMIT_AUTHOR: "Continuous Integration"
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install 'dvc[s3]'
          pip install --upgrade "zenml[server]==0.90.0"
          pip show zenml

      - name: Start ZenML server
        run: |
          nohup zenml up &  # Run ZenML server in background

      - name: Check DVC version and pull existing model
        run: |
          dvc --version
          dvc remote list
          dvc pull saved_model/model.pkl || echo "No existing model found to pull."

      - name: Train and Evaluate model (only if model doesn't exist)
        run: |
          set -e
          if [ ! -f saved_model/model.pkl.dvc ]; then
            echo "No model found. Training new model..."    
            python run_pipeline.py --load-data --path "data/SMSSpamCollection" || { echo "Data loading failed"; exit 1; }
            echo "Data loaded successfully."

            echo "Starting model training..."
            python run_pipeline.py --train-model --num-epochs 1 --num-of-labels 1 --learning-rate 0.00001 || { echo "Training failed"; exit 1; }
            echo "Training completed."

            echo "Running model evaluation..."
            python run_pipeline.py --evaluate-model || { echo "Evaluation failed"; exit 1; }
            echo "Model evaluated successfully."
          else
            echo "Model already exists. Skipping training."
          fi

      - name: Accuracy check
        run: |
          set -e
          if [ ! -f accuracy.py ]; then
            python accuracy.py
          fi
          if [ -f accuracy.txt ]; then
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "Abinash200501@users.noreply.github.com"
          git add accuracy.txt
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo "No changes to commit"
          
          # Push using GitHub Actions token
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Abinash200501/ML_END_TO_END.git HEAD:main
          fi

      - name: Threshold check
        run: |
          set -e
          echo "Checking model accuracy threshold..."
          if [ ! -f accuracy.txt ]; then
            echo "Error: accuracy.txt not found. Evaluation step may have failed."
            exit 1
          fi
        
          accuracy=$(grep "Accuracy:" accuracy.txt | awk '{print $2}')
          threshold=0.90
          echo "accuracy=$accuracy" >> $GITHUB_OUTPUT
          if (( $(echo "$accuracy < $threshold" | bc -l) )); then
            echo "Model accuracy $accuracy% is below threshold $threshold. Failing..."
            exit 1
          else
            echo "Model accuracy $accuracy% meets threshold $threshold."
          fi
      - name: Checking DVC remote
        run: |
          echo "Configured DVC remotes:"
          dvc remote list || echo "No remotes found."
          
      - name: Configure and track model with DVC
        if: success()
        run: |
          if [ ! -d .dvc ]; then
            dvc init
          fi
          if ! dvc remote list | grep -q '^myremote'; then
            dvc remote add -d myremote s3://${{ secrets.AWS_S3_BUCKET }}/saved_model
          fi
          if [ -f saved_model/model.pkl ]; then
            dvc add saved_model/model.pkl
          fi

      - name: Checking DVC remote
        run: |
          echo "Configured DVC remotes:"
          dvc remote list || echo "No remotes found."

      - name: Commit and push DVC changes only if model changed
        if: success()
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "Abinash200501@users.noreply.github.com"
          if [ -f saved_model/model.pkl.dvc ]; then
            git add saved_model/model.pkl.dvc .gitignore
          fi
          if ! git diff --cached --quiet; then
            echo "Changes detected in model. Committing..."
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Abinash200501/ML_END_TO_END.git HEAD:main
            dvc push          
          else
            echo "No changes in model. Skipping commit and push."
          fi
          

  cd_pipeline:
    runs-on: self-hosted
    needs: ci_pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/myenv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python & DVC
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          if [ ! -d ~/myenv ]; then
            python3 -m venv ~/myenv
          fi
          source ~/myenv/bin/activate
          pip install --upgrade pip
          if ! pip show dvc >/dev/null 2>&1; then
            pip install dvc[s3] boto3 --cache-dir /tmp/pip_cache
          fi

      - name: Cache DVC model
        uses: actions/cache@v3
        with:
          path: .dvc/cache
          key: ${{ runner.os }}-dvc-${{ hashFiles('saved_model/model.pkl.dvc') }}

      - name: Checking DVC remote
        run: |
          echo "Configured DVC remotes:"
          dvc remote list || echo "No remotes found."

      - name: Get model from DVC
        run: |
          source ~/myenv/bin/activate
          if ! dvc remote list | grep -q '^myremote'; then
            dvc remote add myremote s3://${{ secrets.AWS_S3_BUCKET }}/saved_model
            dvc remote default myremote
          fi
          dvc pull saved_model/model.pkl || echo "DVC pull completed"
          ls -lh saved_model/


      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          source ~/myenv/bin/activate
          docker build --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:latest \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Pull latest image and cleanup
        run: |
          source ~/myenv/bin/activate
          containers=$(docker ps -q)
          if [ -n "$containers" ]; then
              docker rm -f $containers
          fi
          docker image prune -f
          docker pull ${{ steps.login-ecr.outputs.registry }}/\
          ${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Debug ECR registry
        run: | 
          echo "ECR REGISTRY = "$ECR_REGISTRY"
          echo "ECR_REPOSITORY_NAME: "$ECR_REPOSITORY"

      - name: Run Docker container
        run: |
          source ~/myenv/bin/activate
          docker run -d -p 8000:8000 --name=spam_classifier -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{ steps.login-ecr.outputs.registry }}/\
          ${{ secrets.ECR_REPOSITORY_NAME }}:latest


      - name: Cleanup
        run: |
          source ~/myenv/bin/activate
          rm -f saved_model/model.pkl
          docker system prune -f
